# run rendertemplates -config dependabot-config.yaml -skip-data-dir
templates:
  - from: dependabot.tmpl
    render:
      - to: dependabot.yml
        localSets:
          dailyGoEcosystem:
            packageEcosystem: "gomod"
            scheduleInterval: "daily"
            commitMsgPrefix: "gomod"
            commitIncludeScope: "true"
            labels:
              - "go"
              - "skip-review"
              - "area/dependency"
          dailyDockerEcosystem:
            packageEcosystem: "docker"
            scheduleInterval: "daily"
            commitMsgPrefix: "docker"
            commitIncludeScope: "true"
            labels:
              - "docker"
              - "area/dependency"
        jobConfigs:
          - repoName: "github.com/kyma-project/third-party-images"
            jobs:
              - jobConfig:
                  directory: "/k8s-tools"
                inheritedConfigs:
                  local:
                    - "dailyDockerEcosystem"
