dist:
  module: go.opentelemetry.io/collector/cmd/otelcorecol
  name: otelcorecol
  description: OpenTelemetry Collector binary for Kyma.
  version: OTEL_VERSION
  otelcol_version: OTEL_VERSION

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/opencensusreceiver vOTEL_VERSION

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor vOTEL_VERSION
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor vOTEL_VERSION

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter vOTEL_VERSION
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter vOTEL_VERSION
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter vOTEL_VERSION

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension vOTEL_VERSION

replaces:
  - cloud.google.com/go/compute => cloud.google.com/go/compute v1.12.1
  - cloud.google.com/go/compute/metadata => cloud.google.com/go/compute/metadata v0.2.1
