dist:
  module: go.opentelemetry.io/collector/cmd/otelcorecol
  name: kyma-otelcol
  description: OpenTelemetry Collector binary for Kyma.
  version: OTEL_VERSION
  otelcol_version: OTEL_VERSION
  output_path: .

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/opencensusreceiver vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/httpcheckreceiver vOTEL_VERSION

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor vOTEL_VERSION
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor vOTEL_VERSION

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter vOTEL_VERSION
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter vOTEL_VERSION
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter vOTEL_VERSION

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension vOTEL_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage vOTEL_VERSION

replaces:
  # a list of "replaces" directives that will be part of the resulting go.mod
  - github.com/go-resty/resty/v2 => github.com/go-resty/resty/v2 v2.12.0
