name: Pre-submit Telemetry Self Monitor Image Builder

on:
  pull_request_target:
    paths:
      - "telemetry-self-monitor/**"

jobs:
  envs:
    runs-on: ubuntu-latest
    outputs:
      build-args: ${{ steps.prepare-envs.outputs.build-args }}
      prometheus-version: ${{ steps.load-envs.outputs.PROMETHEUS_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Fetch new env file
        run: |
          git fetch origin ${{ github.event.pull_request.head.sha }}
          git checkout ${{ github.event.pull_request.head.sha }} --no-overlay -- telemetry-self-monitor/envs

      - name: Prepare Envs
        id: prepare-envs
        run: |
          {
          # this creates a multiline string with the envs. 
          # Everything between `build-args<<BUILD_ARGS` and BUILD_ARGS will be content of the build-args variable.
          echo 'build-args<<BUILD_ARGS'
          cat telemetry-self-monitor/envs
          echo BUILD_ARGS

          } >> "$GITHUB_OUTPUT"

      - name: load envs into output
        id: load-envs
        run: |
          cat telemetry-self-monitor/envs >> "$GITHUB_OUTPUT"

  build-image:
    needs: envs
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: tpi/telemetry-self-monitor
      dockerfile: telemetry-self-monitor/Dockerfile
      context: .
      build-args: ${{ needs.envs.outputs.build-args }}
  list-images:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: List images
        run: |
          echo "${{ needs.build-image.outputs.images }}"
